to_addr: 'recipient@example.com'
cc_addr: 'ccrecipient@example.com'
m_subject: 'Results of webpage testing'
to_name: 'Name'
greeting: 'Hi'
intro: 'Here are the URLs that I just tested along with relevant data:'
username: 'author@example.com'
password: 'yourgmailpassword'
location: 'Dulles'
platform: 'Chrome'
